### INPUT
# datadir: ./data/basket
datadir: ../nerf-pytorch/data/basket
dataset_type: llff
expname: basket

factor: 1
llffhold: 8

### TRAINING
N_iter: 200001
N_rand: 1024
N_samples: 64
N_importance: 64

use_viewdirs: True
raw_noise_std: 1e0

i_video: 30000
i_img: 5000
spherify: true
