### INPUT
# datadir: ../nerf-pytorch/data/nerf_llff_data/fern
datadir: ./data/nerf_llff_data/fern

dataset_type: llff
expname: fern

N_rand: 1024
N_samples: 64
N_importance: 64

factor: 8
llffhold: 8
i_video: 20000
N_iter: 60000
i_img: 2000
use_viewdirs: True
raw_noise_std: 1e0

